// constants
import { TRANSACTION_CATEGORY_OPTIONS_OBJECT_EXPENSES } from "./expenses";
import { TRANSACTION_CATEGORY_OPTIONS_OBJECT_INCOMES } from "./incomes";
import { TRANSACTION_CATEGORY_OPTIONS_OBJECT_INITIAL } from "./initial";
import { TRANSACTION_CATEGORY_OPTIONS_OBJECT_KEYS } from "./keys";

//--------------------------------------------------------------------------------------------------//

export const TRANSACTION_CATEGORY_OPTIONS_OBJECT = Object.freeze({
  [TRANSACTION_CATEGORY_OPTIONS_OBJECT_KEYS[0]]:
    TRANSACTION_CATEGORY_OPTIONS_OBJECT_INITIAL,

  [TRANSACTION_CATEGORY_OPTIONS_OBJECT_KEYS[1]]:
    TRANSACTION_CATEGORY_OPTIONS_OBJECT_EXPENSES,

  [TRANSACTION_CATEGORY_OPTIONS_OBJECT_KEYS[2]]:
    TRANSACTION_CATEGORY_OPTIONS_OBJECT_INCOMES,
} as const);
